services:
  moirai-jobs-api:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.moirai.jobs.api
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=moirai-jobs-api
    networks:
      nemesis-starter_nemesis:
        ipv4_address: 172.20.0.10
    container_name: moirai-jobs-api
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"

  restrictions-ports:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.restrictions-ports
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=restrictions-ports
    networks:
      - nemesis-starter_nemesis
    container_name: restrictions-ports
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-service:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.paloalto-service
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-service
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-service
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-host:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.paloalto-host
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-host
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-host
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-rule:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.paloalto-rule
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-rule
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-rule
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-nat:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.paloalto-nat
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-nat
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-nat
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  fortinet-service:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.fortinet-service
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=fortinet-service
    networks:
      - nemesis-starter_nemesis
    container_name: fortinet-service
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  fortinet-address:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.fortinet-address
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=fortinet-address
    networks:
      - nemesis-starter_nemesis
    container_name: fortinet-address
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  fortinet-ippool:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.fortinet-ippool
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=fortinet-ippool
    networks:
      - nemesis-starter_nemesis
    container_name: fortinet-ippool
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  fortinet-virtual-ip:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.fortinet-virtual-ip
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=fortinet-policy
    networks:
      - nemesis-starter_nemesis
    container_name: fortinet-virtual-ip
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  fortinet-central-snat:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.fortinet-central-snat
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=fortinet-central-snat
    networks:
      - nemesis-starter_nemesis
    container_name: fortinet-central-snat
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  fortinet-policy:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.fortinet-policy
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=fortinet-policy
    networks:
      - nemesis-starter_nemesis
    container_name: fortinet-policy
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  nemesis-nat:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.nemesis-nat
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=nemesis-nat
    networks:
      - nemesis-starter_nemesis
    container_name: nemesis-nat
    environment:
      - ENV=tesp5
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

networks:
  nemesis-starter_nemesis:
    external: true
