services:
  moirai-jobs-api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=moirai-jobs-api
    networks:
      nemesis-starter_nemesis:
        ipv4_address: 172.20.0.10
    container_name: moirai-jobs-api
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"

  paloalto-host:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-host
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-host
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-ikegateway:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-ikegateway
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-ikegateway
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-tunnel:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-tunnel
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-tunnel
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-zone:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-zone
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-zone
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-rule:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-rule
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-rule
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-router:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-router
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-router
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-ipsec:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-ipsec
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-ipsec
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api
  
  paloalto-pbf:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-pbf
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-pbf
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  nemesis-vpn:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=nemesis-vpn
        - BRANCH=develop 
    networks:
      - nemesis-starter_nemesis
    container_name: nemesis-vpn
    environment:
      - ENV=${env}
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

networks:
  nemesis-starter_nemesis:
    external: true
