services:
  moirai-jobs-api:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.moirai.jobs.api
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=moirai-jobs-api
    networks:
      nemesis-starter_nemesis:
        ipv4_address: 172.20.0.10
    container_name: moirai-jobs-api
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"

  nasxt-tier1:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.nsxt-tier1
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=nasxt-tier1
    networks:
      - nemesis-starter_nemesis
    container_name: nasxt-tier1
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  nsxt-locale-service:
    build:
      context: ../
      dockerfile: docker/dockerfiles/Dockerfile.nsxt-locale-service
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=nsxt-locale-service
    networks:
      - nemesis-starter_nemesis
    container_name: nsxt-locale-service
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  nsxt-security-policy:
    build:
      context: ../
      dockerfile: docker/Dockerfile.nsxt-security-policy
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=nsxt-security-policy
    networks:
      - nemesis-starter_nemesis
    container_name: nsxt-security-policy
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  paloalto-tag:
    build:
      context: ../
      dockerfile: docker/Dockerfile.paloalto-tag
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=paloalto-tag
    networks:
      - nemesis-starter_nemesis
    container_name: paloalto-tag
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  vmware-virtual-machine:
    build:
      context: ../
      dockerfile: docker/Dockerfile.vmware-virtual-machine
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=vmware-virtual-machine
    networks:
      - nemesis-starter_nemesis
    container_name: vmware-virtual-machine
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  nemesis-organization:
    build:
      context: ../
      dockerfile: docker/Dockerfile.nemesis-organization
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=nemesis-organization
    networks:
      - nemesis-starter_nemesis
    container_name: nemesis-organization
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  fortinet-policy:
    build:
      context: ../
      dockerfile: docker/Dockerfile.fortinet-policy
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=fortinet-policy
    networks:
      - nemesis-starter_nemesis
    container_name: fortinet-policy
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

  nemesis-vpn:
    build:
      context: ../
      dockerfile: docker/Dockerfile.nemesis-vpn
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
        - SERVICE_NAME=nemesis-vpn
    networks:
      - nemesis-starter_nemesis
    container_name: nemesis-vpn
    environment:
      - ENV=dev
      - ETCD_URL=nemesis-etcd:2379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "logging=promtail"
    depends_on:
      - moirai-jobs-api

networks:
  nemesis-starter_nemesis:
    external: true